import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import {
  Outlet,
  Link,
  createRootRouteWithContext,
  useRouter,
  HeadContent,
  Scripts,
} from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";

import appCss from "../styles.css?url";
import { AppLogo } from "../components/pngto/app-logo";
import {
  APP_HEAD_LINKS,
  APP_ICON,
  APP_PWA_META,
  APP_THEME_COLOR,
  APP_VIEWPORT,
  appIconHref,
} from "../lib/app-brand";
import { useT } from "../hooks/use-t";
import { LocaleProvider } from "../hooks/use-locale";
import { ProjectsProvider } from "../hooks/use-projects";
import { ThemeProvider } from "../hooks/use-theme";
import { themeInitScript } from "../lib/theme";
import { DocumentHead } from "../components/pngto/document-head";
import { Toaster } from "../components/ui/sonner";
import { reportLovableError } from "../lib/lovable-error-reporting";

function NotFoundComponent() {
  const { t } = useT();

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <div className="mb-6 flex justify-center">
          <AppLogo size="lg" shadow />
        </div>
        <h1 className="text-7xl font-bold text-foreground">{t("error404.title")}</h1>
        <h2 className="mt-4 text-xl font-semibold text-foreground">{t("error404.heading")}</h2>
        <p className="mt-2 text-sm text-muted-foreground">{t("error404.description")}</p>
        <div className="mt-6">
          <Link
            to="/"
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
            data-testid="error404-go-home"
          >
            {t("error404.goHome")}
          </Link>
        </div>
      </div>
    </div>
  );
}

function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) {
  const { t } = useT();
  const router = useRouter();
  useEffect(() => {
    reportLovableError(error, { boundary: "tanstack_root_error_component" });
  }, [error]);

  return (
    <div className="flex min-h-screen items-center justify-center bg-background px-4">
      <div className="max-w-md text-center">
        <div className="mb-6 flex justify-center">
          <AppLogo size="lg" shadow />
        </div>
        <h1 className="text-xl font-semibold tracking-tight text-foreground">
          {t("errorPage.heading")}
        </h1>
        <p className="mt-2 text-sm text-muted-foreground">{t("errorPage.description")}</p>
        <div className="mt-6 flex flex-wrap justify-center gap-2">
          <button
            onClick={() => {
              router.invalidate();
              reset();
            }}
            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
            data-testid="error-page-retry"
          >
            {t("errorPage.tryAgain")}
          </button>
          <a
            href="/"
            className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
            data-testid="error-page-go-home"
          >
            {t("errorPage.goHome")}
          </a>
        </div>
      </div>
    </div>
  );
}

export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      { name: "viewport", content: APP_VIEWPORT },
      { title: "PNGtoHTMLapp — Screenshot to clean HTML" },
      {
        name: "description",
        content:
          "Upload a UI screenshot and get clean, semantic HTML and CSS generated by AI. Sandboxed preview, copy, and download.",
      },
      { name: "theme-color", content: APP_THEME_COLOR },
      { name: "apple-mobile-web-app-title", content: "PNGtoHTML" },
      ...APP_PWA_META,
      { property: "og:title", content: "PNGtoHTMLapp" },
      {
        property: "og:description",
        content: "Turn UI screenshots into clean, semantic HTML with AI.",
      },
      { property: "og:type", content: "website" },
      { property: "og:image", content: appIconHref(APP_ICON.android512) },
      { property: "og:image:width", content: "512" },
      { property: "og:image:height", content: "512" },
      { name: "twitter:card", content: "summary" },
      { name: "twitter:image", content: appIconHref(APP_ICON.android512) },
    ],
    links: [
      ...APP_HEAD_LINKS,
      {
        rel: "stylesheet",
        href: appCss,
      },
    ],
  }),
  shellComponent: RootShell,
  component: RootComponent,
  notFoundComponent: NotFoundComponent,
  errorComponent: ErrorComponent,
});

function RootShell({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <HeadContent />
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body>
        {children}
        <Scripts />
      </body>
    </html>
  );
}

function RootComponent() {
  const { queryClient } = Route.useRouteContext();

  return (
    <LocaleProvider>
      <ThemeProvider>
        <ProjectsProvider>
          <QueryClientProvider client={queryClient}>
            {/* Required: nested routes render here. Removing <Outlet /> breaks all child routes. */}
            <DocumentHead />
            <Outlet />
            <Toaster />
          </QueryClientProvider>
        </ProjectsProvider>
      </ThemeProvider>
    </LocaleProvider>
  );
}
