import { createFileRoute, Link, useNavigate, useSearch } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { useCallback, useEffect, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { AlertTriangle, RotateCcw, Sparkles } from "lucide-react";

import {
  continueHtml,
  generateHtml,
  refineHtml,
  runOcr,
  type ServerResult,
} from "@/lib/generate.functions";
import { createApiError, createSensor, PHASE_LABELS } from "@/lib/generation-diagnostics";
import { CapabilityCards, TrustStrip } from "@/components/pngto/capability-cards";
import { AdvancedSettings, AppWindow, TopCreditBar } from "@/components/pngto/home-workspace";
import { VisualSidebar } from "@/components/pngto/sidebar-nav";
import { UploadDropzone, type UploadedImage } from "@/components/pngto/upload-dropzone";
import { ImagePreview } from "@/components/pngto/image-preview";
import { GenerationOptionsPanel } from "@/components/pngto/generation-options";
import { ResultTabs } from "@/components/pngto/result-tabs";
import { RefinementBox } from "@/components/pngto/refinement-box";
import { LoadingSteps } from "@/components/pngto/loading-steps";
import { Button } from "@/components/ui/button";
import { useProjects } from "@/hooks/use-projects";
import type { SavedProject } from "@/types/project";
import type {
  ApiError,
  GenerationOptions,
  GenerationSensor,
  GenerateHtmlResult,
} from "@/types/generation";

type IndexSearch = {
  project?: string;
};

export const Route = createFileRoute("/")({
  validateSearch: (search: Record<string, unknown>): IndexSearch => ({
    project: typeof search.project === "string" ? search.project : undefined,
  }),
  head: () => ({
    meta: [
      { title: "PNGtoHTMLapp — Screenshot to clean HTML" },
      {
        name: "description",
        content:
          "Upload a UI screenshot and get clean, semantic HTML and CSS generated by AI. Sandboxed preview, copy, and download.",
      },
      { property: "og:title", content: "PNGtoHTMLapp" },
      {
        property: "og:description",
        content: "Turn UI screenshots into clean, semantic HTML with AI.",
      },
    ],
  }),
  component: Index,
});

const DEFAULT_OPTIONS: GenerationOptions = {
  outputMode: "static",
  stylingMode: "vanilla-css",
  responsiveness: "adaptive",
  accessibilityLevel: "strict",
  additionalInstructions:
    "Recreate the screenshot as closely as possible. Preserve layout, spacing, colors, typography, visible text, buttons, cards, forms, and navigation. Do not invent unrelated content.",
};

type RetryAction = "generate" | "continue" | "refine";

export function Index() {
  const { project: projectIdFromUrl } = useSearch({ from: "/", strict: false });
  const navigate = useNavigate();
  const { getProject, saveFromGeneration } = useProjects();

  const [image, setImage] = useState<UploadedImage | null>(null);
  const [loadedProject, setLoadedProject] = useState<SavedProject | null>(null);
  const [activeProjectId, setActiveProjectId] = useState<string | null>(null);
  const [options, setOptions] = useState<GenerationOptions>(DEFAULT_OPTIONS);
  const [result, setResult] = useState<GenerateHtmlResult | null>(null);
  const [error, setError] = useState<ApiError | null>(null);
  const [sensor, setSensor] = useState<GenerationSensor>(createSensor("validating", "idle"));
  const [lastRefineInstruction, setLastRefineInstruction] = useState<string | null>(null);
  const [lastRetryAction, setLastRetryAction] = useState<RetryAction>("generate");
  const [saveNotice, setSaveNotice] = useState<string | null>(null);

  const ocrFn = useServerFn(runOcr);
  const generateFn = useServerFn(generateHtml);
  const continueFn = useServerFn(continueHtml);
  const refineFn = useServerFn(refineHtml);

  useEffect(() => {
    if (!projectIdFromUrl) return;
    const project = getProject(projectIdFromUrl);
    if (!project) return;
    setLoadedProject(project);
    setActiveProjectId(project.id);
    setOptions(project.options);
    setResult(project.result);
    setImage(null);
    setError(null);
    setSensor(createSensor("done", "success"));
  }, [projectIdFromUrl, getProject]);

  const persistResult = useCallback(
    async (data: GenerateHtmlResult) => {
      const source = image;
      const fallback = loadedProject ?? (activeProjectId ? getProject(activeProjectId) : null);

      if (!source && !fallback) return;

      const savedId = await saveFromGeneration({
        fileName: source?.file.name ?? fallback!.fileName,
        imageWidth: source?.width ?? fallback!.imageWidth,
        imageHeight: source?.height ?? fallback!.imageHeight,
        imageDataUrl: source?.dataUrl ?? fallback!.thumbnailDataUrl,
        options,
        result: data,
        projectId: activeProjectId ?? fallback?.id,
      });

      if (savedId) {
        setActiveProjectId(savedId);
        setSaveNotice("Saved to Projects");
        window.setTimeout(() => setSaveNotice(null), 3000);
      }
    },
    [activeProjectId, getProject, image, loadedProject, options, saveFromGeneration],
  );

  const handleResult = (res: ServerResult) => {
    if (res.ok) {
      setResult(res.data);
      setError(null);
      setSensor(createSensor("done", "success"));
      void persistResult(res.data);
    } else {
      setError(res.error);
      setSensor(createSensor(res.error.phase ?? "failed", "failed", res.error.diagnostic));
    }
  };

  const resetForNewImage = () => {
    setResult(null);
    setError(null);
    setLoadedProject(null);
    setActiveProjectId(null);
    setSaveNotice(null);
    setLastRetryAction("generate");
    setLastRefineInstruction(null);
    setSensor(createSensor("validating", "idle"));
    void navigate({ to: "/", search: {} });
  };

  const generateMut = useMutation({
    mutationFn: async (optionsOverride?: GenerationOptions): Promise<ServerResult> => {
      if (!image) throw new Error("No image");
      const runOptions = optionsOverride ?? options;

      setError(null);
      setLastRetryAction("generate");
      setLastRefineInstruction(null);
      setSensor(createSensor("validating"));
      setSensor(createSensor("rate_limited_check"));
      setSensor({
        ...createSensor("uploading_to_blob"),
        progress: 10,
        message: "Preparing image for OCR...",
      });
      const ocr = await ocrFn({
        data: { imageBase64: image.base64, mimeType: image.mimeType },
      });
      if (!ocr.ok) return { ok: false, error: ocr.error };

      setSensor(createSensor("ocr"));
      setSensor({
        ...createSensor("synthesizing"),
        progress: 45,
      });
      return generateFn({
        data: {
          imageBase64: image.base64,
          mimeType: image.mimeType,
          ocrMarkdown: ocr.ocrMarkdown,
          options: runOptions,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => {
      const apiError = createApiError(
        "SERVER_ERROR",
        (e as Error).message ?? "Unexpected error",
        "failed",
      );
      setError(apiError);
      setSensor(createSensor("failed", "failed", apiError.diagnostic));
    },
  });

  const continueMut = useMutation({
    mutationFn: async (): Promise<ServerResult> => {
      if (!result) throw new Error("No prior result");

      setError(null);
      setLastRetryAction("continue");
      setSensor({
        ...createSensor("synthesizing"),
        progress: 75,
        message: "Continuing code generation...",
      });
      return continueFn({
        data: {
          prior: {
            html: result.html,
            css: result.css,
            javascript: result.javascript,
          },
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => {
      const apiError = createApiError(
        "SERVER_ERROR",
        (e as Error).message ?? "Unexpected error",
        "failed",
      );
      setError(apiError);
      setSensor(createSensor("failed", "failed", apiError.diagnostic));
    },
  });

  const refineMut = useMutation({
    mutationFn: async (instruction: string) => {
      if (!result) throw new Error("No prior result");
      setLastRetryAction("refine");
      setLastRefineInstruction(instruction);
      setError(null);
      setSensor({
        ...createSensor("synthesizing"),
        progress: 10,
        message: "Applying your refinement...",
      });
      return refineFn({
        data: {
          prior: {
            html: result.html,
            css: result.css,
            javascript: result.javascript,
          },
          instruction,
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => {
      const apiError = createApiError(
        "SERVER_ERROR",
        (e as Error).message ?? "Unexpected error",
        "failed",
      );
      setError(apiError);
      setSensor(createSensor("failed", "failed", apiError.diagnostic));
    },
  });

  const busy = generateMut.isPending || continueMut.isPending || refineMut.isPending;
  const primaryButtonLabel = continueMut.isPending
    ? "Continuing..."
    : busy
      ? "Generating..."
      : result
        ? "Continue code generation"
        : "Generate HTML";

  return (
    <div className="visual-shell min-h-dvh">
      <VisualSidebar />

      <div className="min-h-dvh pb-[4.5rem] md:pl-16 md:pb-0">
        <TopCreditBar />

        <main className="mx-auto max-w-5xl px-4 py-6 pb-8 sm:px-6 sm:py-10 sm:pb-16">
          <div className="relative">
            <AppWindow>
              <div className="space-y-5">
                {image ? (
                  <ImagePreview
                    image={image}
                    options={options}
                    busy={busy}
                    onForensicGenerate={(nextOptions) => {
                      setOptions(nextOptions);
                      generateMut.mutate(nextOptions);
                    }}
                    onRemove={() => {
                      setImage(null);
                      resetForNewImage();
                    }}
                  />
                ) : loadedProject ? (
                  <LoadedProjectBanner project={loadedProject} onClear={resetForNewImage} />
                ) : (
                  <UploadDropzone
                    onFile={(img) => {
                      setImage(img);
                      setLoadedProject(null);
                      setActiveProjectId(null);
                      setResult(null);
                      setError(null);
                      setSaveNotice(null);
                      setLastRetryAction("generate");
                      setLastRefineInstruction(null);
                      setSensor(createSensor("validating", "idle"));
                      void navigate({ to: "/", search: {} });
                    }}
                    onError={(message) =>
                      setError(createApiError("INVALID_FILE", message, "validating"))
                    }
                  />
                )}

                <AdvancedSettings>
                  <GenerationOptionsPanel value={options} onChange={setOptions} disabled={busy} />
                </AdvancedSettings>

                <Button
                  className="h-11 w-full bg-primary text-primary-foreground hover:bg-primary-hover"
                  size="lg"
                  disabled={(!image && !result) || busy}
                  onClick={() => {
                    if (result) continueMut.mutate();
                    else generateMut.mutate(undefined);
                  }}
                >
                  <Sparkles className="h-4 w-4" aria-hidden />
                  {primaryButtonLabel}
                </Button>

                {error && (
                  <DiagnosticErrorPanel
                    error={error}
                    onRetry={() => {
                      if (lastRetryAction === "continue" && result) continueMut.mutate();
                      else if (lastRetryAction === "refine" && lastRefineInstruction && result)
                        refineMut.mutate(lastRefineInstruction);
                      else generateMut.mutate(undefined);
                    }}
                  />
                )}

                {busy && <LoadingSteps sensor={sensor} />}
              </div>
            </AppWindow>
          </div>

          {result && (
            <section className="mt-8 space-y-4 rounded-xl border border-shell-border bg-shell-elevated p-5">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  <h2 className="text-sm font-medium text-foreground">Generated output</h2>
                  {saveNotice && (
                    <span className="rounded-full bg-emerald-500/15 px-2 py-0.5 text-[10px] font-medium text-emerald-700 dark:text-emerald-200">
                      {saveNotice}
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-3">
                  {activeProjectId && (
                    <Link
                      to="/projects/$projectId"
                      params={{ projectId: activeProjectId }}
                      className="text-xs text-info hover:underline"
                    >
                      View in Projects
                    </Link>
                  )}
                  <button
                    type="button"
                    onClick={resetForNewImage}
                    className="text-xs text-shell-muted hover:text-foreground"
                  >
                    New upload
                  </button>
                </div>
              </div>
              <ResultTabs result={result} />
              <div className="border-t border-shell-border pt-4">
                <RefinementBox onSubmit={(i) => refineMut.mutate(i)} disabled={busy} />
              </div>
            </section>
          )}

          {!result && !busy && <CapabilityCards />}
          <TrustStrip />
        </main>
      </div>
    </div>
  );
}

function LoadedProjectBanner({ project, onClear }: { project: SavedProject; onClear: () => void }) {
  return (
    <div className="workspace-panel flex items-center gap-3 p-3">
      <img src={project.thumbnailDataUrl} alt="" className="h-16 w-16 rounded-md object-cover" />
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-medium text-workspace-foreground">{project.name}</p>
        <p className="text-xs text-workspace-muted">
          Opened from Projects · {project.fileName} · continue refining or generate from a new
          screenshot
        </p>
      </div>
      <button
        type="button"
        onClick={onClear}
        className="shrink-0 text-xs text-workspace-muted hover:text-workspace-foreground"
      >
        Clear
      </button>
    </div>
  );
}

function DiagnosticErrorPanel({ error, onRetry }: { error: ApiError; onRetry: () => void }) {
  const diagnostic = error.diagnostic;
  const phase = error.phase ?? "failed";

  return (
    <div
      role="alert"
      className="space-y-3 rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-xs text-destructive"
    >
      <div className="flex items-start gap-2">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden />
        <div className="min-w-0 space-y-1">
          <div className="text-sm font-medium">{diagnostic?.title ?? error.message}</div>
          <div className="text-destructive/80">Phase: {PHASE_LABELS[phase]}</div>
        </div>
      </div>

      <div className="space-y-2 text-destructive/90">
        <p>{diagnostic?.detail ?? error.message}</p>
        {diagnostic && <p>Likely cause: {diagnostic.likelyCause}</p>}
        {diagnostic && <p>Suggested fix: {diagnostic.suggestedFix}</p>}
      </div>

      {diagnostic?.retryable && (
        <Button
          size="sm"
          variant="outline"
          className="h-8 border-destructive/30 bg-workspace-surface text-destructive hover:bg-destructive/10"
          onClick={onRetry}
        >
          <RotateCcw className="h-3.5 w-3.5" aria-hidden />
          Try again
        </Button>
      )}
    </div>
  );
}
