import { createFileRoute } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { AlertTriangle, RotateCcw, Sparkles } from "lucide-react";

import { generateHtml, refineHtml, runOcr, type ServerResult } from "@/lib/generate.functions";
import { createApiError, createSensor, PHASE_LABELS } from "@/lib/generation-diagnostics";
import { UploadDropzone, type UploadedImage } from "@/components/pngto/upload-dropzone";
import { ImagePreview } from "@/components/pngto/image-preview";
import { GenerationOptionsPanel } from "@/components/pngto/generation-options";
import { ResultTabs } from "@/components/pngto/result-tabs";
import { RefinementBox } from "@/components/pngto/refinement-box";
import { LoadingSteps } from "@/components/pngto/loading-steps";
import { Button } from "@/components/ui/button";
import type {
  ApiError,
  GenerationOptions,
  GenerationSensor,
  GenerateHtmlResult,
} from "@/types/generation";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "PNGtoHTMLapp — Screenshot to clean HTML" },
      {
        name: "description",
        content:
          "Upload a UI screenshot and get clean, semantic HTML and CSS generated by AI. Sandboxed preview, copy, and download.",
      },
      { property: "og:title", content: "PNGtoHTMLapp" },
      {
        property: "og:description",
        content: "Turn UI screenshots into clean, semantic HTML with AI.",
      },
    ],
  }),
  component: Index,
});

const DEFAULT_OPTIONS: GenerationOptions = {
  outputMode: "static",
  stylingMode: "vanilla-css",
  responsiveness: "mobile-first",
  accessibilityLevel: "standard",
  additionalInstructions:
    "Generate clean, semantic, accessible HTML and CSS. Prefer modern standards. Keep it simple and maintainable.",
};

function Index() {
  const [image, setImage] = useState<UploadedImage | null>(null);
  const [options, setOptions] = useState<GenerationOptions>(DEFAULT_OPTIONS);
  const [result, setResult] = useState<GenerateHtmlResult | null>(null);
  const [error, setError] = useState<ApiError | null>(null);
  const [sensor, setSensor] = useState<GenerationSensor>(createSensor("validating", "idle"));
  const [lastRefineInstruction, setLastRefineInstruction] = useState<string | null>(null);

  const ocrFn = useServerFn(runOcr);
  const generateFn = useServerFn(generateHtml);
  const refineFn = useServerFn(refineHtml);

  const handleResult = (res: ServerResult) => {
    if (res.ok) {
      setResult(res.data);
      setError(null);
      setSensor(createSensor("done", "success"));
    } else {
      setError(res.error);
      setSensor(createSensor(res.error.phase ?? "failed", "failed", res.error.diagnostic));
    }
  };

  const generateMut = useMutation({
    mutationFn: async (): Promise<ServerResult> => {
      if (!image) throw new Error("No image");

      setError(null);
      setLastRefineInstruction(null);
      setSensor(createSensor("validating"));
      setSensor(createSensor("rate_limited_check"));
      setSensor({
        ...createSensor("uploading_to_blob"),
        progress: 10,
        message: "Preparing image for OCR...",
      });
      const ocr = await ocrFn({
        data: { imageBase64: image.base64, mimeType: image.mimeType },
      });
      if (!ocr.ok) return { ok: false, error: ocr.error };

      setSensor(createSensor("ocr"));
      setSensor({
        ...createSensor("synthesizing"),
        progress: 45,
      });
      return generateFn({
        data: {
          imageBase64: image.base64,
          mimeType: image.mimeType,
          ocrMarkdown: ocr.ocrMarkdown,
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => {
      const apiError = createApiError(
        "SERVER_ERROR",
        (e as Error).message ?? "Unexpected error",
        "failed",
      );
      setError(apiError);
      setSensor(createSensor("failed", "failed", apiError.diagnostic));
    },
  });

  const refineMut = useMutation({
    mutationFn: async (instruction: string) => {
      if (!result) throw new Error("No prior result");
      setLastRefineInstruction(instruction);
      setError(null);
      setSensor({
        ...createSensor("synthesizing"),
        progress: 10,
        message: "Applying your refinement...",
      });
      return refineFn({
        data: {
          prior: {
            html: result.html,
            css: result.css,
            javascript: result.javascript,
          },
          instruction,
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => {
      const apiError = createApiError(
        "SERVER_ERROR",
        (e as Error).message ?? "Unexpected error",
        "failed",
      );
      setError(apiError);
      setSensor(createSensor("failed", "failed", apiError.diagnostic));
    },
  });

  const busy = generateMut.isPending || refineMut.isPending;

  return (
    <div className="mx-auto min-h-dvh max-w-350 px-4 py-8 sm:px-6 lg:px-10">
      <header className="mb-8 flex flex-col gap-3 sm:mb-10 sm:flex-row sm:items-end sm:justify-between">
        <div className="min-w-0">
          <div className="mb-2 inline-flex items-center gap-2 rounded-full border border-border bg-white/5 px-3 py-1 text-[11px] text-muted-foreground">
            <Sparkles className="h-3 w-3 text-primary" aria-hidden />
            <span>OCR AI · Mistral OCR + Pixtral Large</span>
          </div>
          <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">PNGtoHTMLapp</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Upload a UI image. Get clean, semantic HTML.
          </p>
        </div>
      </header>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,420px)_minmax(0,1fr)]">
        {/* LEFT: upload + options */}
        <section className="glass-panel space-y-5 p-5">
          {image ? (
            <ImagePreview image={image} onRemove={() => setImage(null)} />
          ) : (
            <UploadDropzone
              onFile={(img) => {
                setImage(img);
                setError(null);
                setLastRefineInstruction(null);
                setSensor(createSensor("validating", "idle"));
              }}
              onError={(message) => setError(createApiError("INVALID_FILE", message, "validating"))}
            />
          )}

          <GenerationOptionsPanel value={options} onChange={setOptions} disabled={busy} />

          <Button
            className="w-full"
            size="lg"
            disabled={!image || busy}
            onClick={() => generateMut.mutate()}
          >
            <Sparkles className="h-4 w-4" aria-hidden />
            {busy ? "Generating…" : "Generate HTML"}
          </Button>

          {error && (
            <DiagnosticErrorPanel
              error={error}
              onRetry={() => {
                if (lastRefineInstruction && result) refineMut.mutate(lastRefineInstruction);
                else generateMut.mutate();
              }}
            />
          )}

          <p className="text-[11px] leading-relaxed text-muted-foreground">
            AI-generated code is an approximation. Review layout, accessibility, and security before
            shipping.
          </p>
        </section>

        {/* RIGHT: result */}
        <section className="glass-panel min-h-125 space-y-4 p-5">
          {busy && <LoadingSteps sensor={sensor} />}

          {!result && !busy && <EmptyState hasImage={!!image} />}

          {result && (
            <>
              <ResultTabs result={result} />
              <div className="border-t border-border pt-4">
                <RefinementBox onSubmit={(i) => refineMut.mutate(i)} disabled={busy} />
              </div>
            </>
          )}
        </section>
      </div>
    </div>
  );
}

function EmptyState({ hasImage }: { hasImage: boolean }) {
  return (
    <div className="flex h-full min-h-100 flex-col items-center justify-center gap-2 text-center">
      <div className="text-sm font-medium">
        {hasImage ? "Ready when you are." : "Upload an image to begin."}
      </div>
      <div className="max-w-sm text-xs text-muted-foreground">
        {hasImage
          ? "Choose your output mode on the left and hit Generate HTML."
          : "Drop a PNG, JPG, or WebP screenshot of a UI, landing page, or component. The AI reconstructs it as clean, semantic HTML/CSS."}
      </div>
    </div>
  );
}

function DiagnosticErrorPanel({ error, onRetry }: { error: ApiError; onRetry: () => void }) {
  const diagnostic = error.diagnostic;
  const phase = error.phase ?? "failed";

  return (
    <div
      role="alert"
      className="glass-inset space-y-3 border-destructive/40 bg-destructive/10 p-3 text-xs text-destructive-foreground"
    >
      <div className="flex items-start gap-2">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden />
        <div className="min-w-0 space-y-1">
          <div className="text-sm font-medium">{diagnostic?.title ?? error.message}</div>
          <div className="text-muted-foreground">Phase: {PHASE_LABELS[phase]}</div>
        </div>
      </div>

      <div className="space-y-2 text-muted-foreground">
        <p>{diagnostic?.detail ?? error.message}</p>
        {diagnostic && <p>Likely cause: {diagnostic.likelyCause}</p>}
        {diagnostic && <p>Suggested fix: {diagnostic.suggestedFix}</p>}
      </div>

      {diagnostic?.retryable && (
        <Button size="sm" variant="outline" className="h-8" onClick={onRetry}>
          <RotateCcw className="h-3.5 w-3.5" aria-hidden />
          Try again
        </Button>
      )}
    </div>
  );
}
