import { createFileRoute } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { AlertTriangle, RotateCcw, Sparkles } from "lucide-react";

import {
  continueHtml,
  generateHtml,
  refineHtml,
  runOcr,
  type ServerResult,
} from "@/lib/generate.functions";
import { createApiError, createSensor, PHASE_LABELS } from "@/lib/generation-diagnostics";
import { CapabilityCards, TrustStrip } from "@/components/pngto/capability-cards";
import { AdvancedSettings, AppWindow, TopCreditBar } from "@/components/pngto/home-workspace";
import { VisualSidebar } from "@/components/pngto/sidebar-nav";
import { UploadDropzone, type UploadedImage } from "@/components/pngto/upload-dropzone";
import { ImagePreview } from "@/components/pngto/image-preview";
import { GenerationOptionsPanel } from "@/components/pngto/generation-options";
import { ResultTabs } from "@/components/pngto/result-tabs";
import { RefinementBox } from "@/components/pngto/refinement-box";
import { LoadingSteps } from "@/components/pngto/loading-steps";
import { Button } from "@/components/ui/button";
import type {
  ApiError,
  GenerationOptions,
  GenerationSensor,
  GenerateHtmlResult,
} from "@/types/generation";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "PNGtoHTMLapp — Screenshot to clean HTML" },
      {
        name: "description",
        content:
          "Upload a UI screenshot and get clean, semantic HTML and CSS generated by AI. Sandboxed preview, copy, and download.",
      },
      { property: "og:title", content: "PNGtoHTMLapp" },
      {
        property: "og:description",
        content: "Turn UI screenshots into clean, semantic HTML with AI.",
      },
    ],
  }),
  component: Index,
});

const DEFAULT_OPTIONS: GenerationOptions = {
  outputMode: "static",
  stylingMode: "vanilla-css",
  responsiveness: "adaptive",
  accessibilityLevel: "strict",
  additionalInstructions:
    "Recreate the screenshot as closely as possible. Preserve layout, spacing, colors, typography, visible text, buttons, cards, forms, and navigation. Do not invent unrelated content.",
};

type RetryAction = "generate" | "continue" | "refine";

function Index() {
  const [image, setImage] = useState<UploadedImage | null>(null);
  const [options, setOptions] = useState<GenerationOptions>(DEFAULT_OPTIONS);
  const [result, setResult] = useState<GenerateHtmlResult | null>(null);
  const [error, setError] = useState<ApiError | null>(null);
  const [sensor, setSensor] = useState<GenerationSensor>(createSensor("validating", "idle"));
  const [lastRefineInstruction, setLastRefineInstruction] = useState<string | null>(null);
  const [lastRetryAction, setLastRetryAction] = useState<RetryAction>("generate");

  const ocrFn = useServerFn(runOcr);
  const generateFn = useServerFn(generateHtml);
  const continueFn = useServerFn(continueHtml);
  const refineFn = useServerFn(refineHtml);

  const handleResult = (res: ServerResult) => {
    if (res.ok) {
      setResult(res.data);
      setError(null);
      setSensor(createSensor("done", "success"));
    } else {
      setError(res.error);
      setSensor(createSensor(res.error.phase ?? "failed", "failed", res.error.diagnostic));
    }
  };

  const resetForNewImage = () => {
    setResult(null);
    setError(null);
    setLastRetryAction("generate");
    setLastRefineInstruction(null);
    setSensor(createSensor("validating", "idle"));
  };

  const generateMut = useMutation({
    mutationFn: async (): Promise<ServerResult> => {
      if (!image) throw new Error("No image");

      setError(null);
      setLastRetryAction("generate");
      setLastRefineInstruction(null);
      setSensor(createSensor("validating"));
      setSensor(createSensor("rate_limited_check"));
      setSensor({
        ...createSensor("uploading_to_blob"),
        progress: 10,
        message: "Preparing image for OCR...",
      });
      const ocr = await ocrFn({
        data: { imageBase64: image.base64, mimeType: image.mimeType },
      });
      if (!ocr.ok) return { ok: false, error: ocr.error };

      setSensor(createSensor("ocr"));
      setSensor({
        ...createSensor("synthesizing"),
        progress: 45,
      });
      return generateFn({
        data: {
          imageBase64: image.base64,
          mimeType: image.mimeType,
          ocrMarkdown: ocr.ocrMarkdown,
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => {
      const apiError = createApiError(
        "SERVER_ERROR",
        (e as Error).message ?? "Unexpected error",
        "failed",
      );
      setError(apiError);
      setSensor(createSensor("failed", "failed", apiError.diagnostic));
    },
  });

  const continueMut = useMutation({
    mutationFn: async (): Promise<ServerResult> => {
      if (!result) throw new Error("No prior result");

      setError(null);
      setLastRetryAction("continue");
      setSensor({
        ...createSensor("synthesizing"),
        progress: 75,
        message: "Continuing code generation...",
      });
      return continueFn({
        data: {
          prior: {
            html: result.html,
            css: result.css,
            javascript: result.javascript,
          },
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => {
      const apiError = createApiError(
        "SERVER_ERROR",
        (e as Error).message ?? "Unexpected error",
        "failed",
      );
      setError(apiError);
      setSensor(createSensor("failed", "failed", apiError.diagnostic));
    },
  });

  const refineMut = useMutation({
    mutationFn: async (instruction: string) => {
      if (!result) throw new Error("No prior result");
      setLastRetryAction("refine");
      setLastRefineInstruction(instruction);
      setError(null);
      setSensor({
        ...createSensor("synthesizing"),
        progress: 10,
        message: "Applying your refinement...",
      });
      return refineFn({
        data: {
          prior: {
            html: result.html,
            css: result.css,
            javascript: result.javascript,
          },
          instruction,
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => {
      const apiError = createApiError(
        "SERVER_ERROR",
        (e as Error).message ?? "Unexpected error",
        "failed",
      );
      setError(apiError);
      setSensor(createSensor("failed", "failed", apiError.diagnostic));
    },
  });

  const busy = generateMut.isPending || continueMut.isPending || refineMut.isPending;
  const primaryButtonLabel = continueMut.isPending
    ? "Continuing..."
    : busy
      ? "Generating..."
      : result
        ? "Continue code generation"
        : "Generate HTML";

  return (
    <div className="visual-shell min-h-dvh">
      <VisualSidebar />

      <div className="min-h-dvh pl-16">
        <TopCreditBar />

        <main className="mx-auto max-w-5xl px-6 py-10 pb-16">
          <div className="relative">
            <AppWindow>
              <div className="space-y-5">
                {image ? (
                  <ImagePreview
                    image={image}
                    onRemove={() => {
                      setImage(null);
                      resetForNewImage();
                    }}
                    variant="light"
                  />
                ) : (
                  <UploadDropzone
                    variant="light"
                    onFile={(img) => {
                      setImage(img);
                      resetForNewImage();
                    }}
                    onError={(message) =>
                      setError(createApiError("INVALID_FILE", message, "validating"))
                    }
                  />
                )}

                <AdvancedSettings>
                  <GenerationOptionsPanel value={options} onChange={setOptions} disabled={busy} />
                </AdvancedSettings>

                <Button
                  className="h-11 w-full bg-[#5b35d5] text-white hover:bg-[#4c2bb8]"
                  size="lg"
                  disabled={(!image && !result) || busy}
                  onClick={() => {
                    if (result) continueMut.mutate();
                    else generateMut.mutate();
                  }}
                >
                  <Sparkles className="h-4 w-4" aria-hidden />
                  {primaryButtonLabel}
                </Button>

                {error && (
                  <DiagnosticErrorPanel
                    error={error}
                    onRetry={() => {
                      if (lastRetryAction === "continue" && result) continueMut.mutate();
                      else if (lastRetryAction === "refine" && lastRefineInstruction && result)
                        refineMut.mutate(lastRefineInstruction);
                      else generateMut.mutate();
                    }}
                  />
                )}

                {busy && <LoadingSteps sensor={sensor} />}
              </div>
            </AppWindow>
          </div>

          {result && (
            <section className="mt-8 space-y-4 rounded-xl border border-[#2a2a31] bg-[#17171a] p-5">
              <div className="flex items-center justify-between gap-3">
                <h2 className="text-sm font-medium text-white">Generated output</h2>
                <button
                  type="button"
                  onClick={() => {
                    setResult(null);
                    setError(null);
                    setSensor(createSensor("validating", "idle"));
                  }}
                  className="text-xs text-[#8b90a0] hover:text-[#c9ccd6]"
                >
                  New upload
                </button>
              </div>
              <ResultTabs result={result} />
              <div className="border-t border-[#2a2a31] pt-4">
                <RefinementBox onSubmit={(i) => refineMut.mutate(i)} disabled={busy} />
              </div>
            </section>
          )}

          {!result && !busy && <CapabilityCards />}
          <TrustStrip />
        </main>
      </div>
    </div>
  );
}

function DiagnosticErrorPanel({ error, onRetry }: { error: ApiError; onRetry: () => void }) {
  const diagnostic = error.diagnostic;
  const phase = error.phase ?? "failed";

  return (
    <div
      role="alert"
      className="space-y-3 rounded-lg border border-red-300 bg-red-50 p-3 text-xs text-red-900"
    >
      <div className="flex items-start gap-2">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden />
        <div className="min-w-0 space-y-1">
          <div className="text-sm font-medium">{diagnostic?.title ?? error.message}</div>
          <div className="text-red-700/80">Phase: {PHASE_LABELS[phase]}</div>
        </div>
      </div>

      <div className="space-y-2 text-red-800/90">
        <p>{diagnostic?.detail ?? error.message}</p>
        {diagnostic && <p>Likely cause: {diagnostic.likelyCause}</p>}
        {diagnostic && <p>Suggested fix: {diagnostic.suggestedFix}</p>}
      </div>

      {diagnostic?.retryable && (
        <Button
          size="sm"
          variant="outline"
          className="h-8 border-red-300 bg-white text-red-900 hover:bg-red-100"
          onClick={onRetry}
        >
          <RotateCcw className="h-3.5 w-3.5" aria-hidden />
          Try again
        </Button>
      )}
    </div>
  );
}
