import { createFileRoute } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { Sparkles } from "lucide-react";

import { generateHtml, refineHtml, type ServerResult } from "@/lib/generate.functions";
import { UploadDropzone, type UploadedImage } from "@/components/pngto/upload-dropzone";
import { ImagePreview } from "@/components/pngto/image-preview";
import { GenerationOptionsPanel } from "@/components/pngto/generation-options";
import { ResultTabs } from "@/components/pngto/result-tabs";
import { RefinementBox } from "@/components/pngto/refinement-box";
import { LoadingSteps } from "@/components/pngto/loading-steps";
import { Button } from "@/components/ui/button";
import type { GenerationOptions, GenerateHtmlResult } from "@/types/generation";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "PNGtoHTMLapp — Screenshot to clean HTML" },
      {
        name: "description",
        content:
          "Upload a UI screenshot and get clean, semantic HTML and CSS generated by AI. Sandboxed preview, copy, and download.",
      },
      { property: "og:title", content: "PNGtoHTMLapp" },
      {
        property: "og:description",
        content: "Turn UI screenshots into clean, semantic HTML with AI.",
      },
    ],
  }),
  component: Index,
});

const DEFAULT_OPTIONS: GenerationOptions = {
  outputMode: "static",
  stylingMode: "vanilla-css",
  responsiveness: "mobile-first",
  accessibilityLevel: "standard",
  additionalInstructions: "Generate clean, semantic, accessible HTML and CSS. Prefer modern standards. Keep it simple and maintainable.",
};

function Index() {
  const [image, setImage] = useState<UploadedImage | null>(null);
  const [options, setOptions] = useState<GenerationOptions>(DEFAULT_OPTIONS);
  const [result, setResult] = useState<GenerateHtmlResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const generateFn = useServerFn(generateHtml);
  const refineFn = useServerFn(refineHtml);

  const handleResult = (res: ServerResult) => {
    if (res.ok) {
      setResult(res.data);
      setError(null);
    } else {
      setError(errorMessage(res.error.code, res.error.message));
    }
  };

  const generateMut = useMutation({
    mutationFn: async () => {
      if (!image) throw new Error("No image");
      return generateFn({
        data: {
          imageBase64: image.base64,
          mimeType: image.mimeType,
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => setError((e as Error).message ?? "Unexpected error"),
  });

  const refineMut = useMutation({
    mutationFn: async (instruction: string) => {
      if (!result) throw new Error("No prior result");
      return refineFn({
        data: {
          prior: {
            html: result.html,
            css: result.css,
            javascript: result.javascript,
          },
          instruction,
          options,
        },
      });
    },
    onSuccess: handleResult,
    onError: (e) => setError((e as Error).message ?? "Unexpected error"),
  });

  const busy = generateMut.isPending || refineMut.isPending;

  return (
    <div className="mx-auto min-h-dvh max-w-[1400px] px-4 py-8 sm:px-6 lg:px-10">
      <header className="mb-8 flex flex-col gap-3 sm:mb-10 sm:flex-row sm:items-end sm:justify-between">
        <div className="min-w-0">
          <div className="mb-2 inline-flex items-center gap-2 rounded-full border border-border bg-white/5 px-3 py-1 text-[11px] text-muted-foreground">
            <Sparkles className="h-3 w-3 text-primary" aria-hidden />
            <span>OCR AI · Mistral OCR + Pixtral Large</span>
          </div>
          <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">PNGtoHTMLapp</h1>
          <p className="mt-1 text-sm text-muted-foreground">
            Upload a UI image. Get clean, semantic HTML.
          </p>
        </div>
      </header>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,420px)_minmax(0,1fr)]">
        {/* LEFT: upload + options */}
        <section className="glass-panel space-y-5 p-5">
          {image ? (
            <ImagePreview image={image} onRemove={() => setImage(null)} />
          ) : (
            <UploadDropzone
              onFile={(img) => {
                setImage(img);
                setError(null);
              }}
              onError={setError}
            />
          )}

          <GenerationOptionsPanel value={options} onChange={setOptions} disabled={busy} />

          <Button
            className="w-full"
            size="lg"
            disabled={!image || busy}
            onClick={() => generateMut.mutate()}
          >
            <Sparkles className="h-4 w-4" aria-hidden />
            {busy ? "Generating…" : "Generate HTML"}
          </Button>

          {error && (
            <div
              role="alert"
              className="glass-inset border-destructive/40 bg-destructive/10 p-3 text-xs text-destructive-foreground"
            >
              {error}
            </div>
          )}

          <p className="text-[11px] leading-relaxed text-muted-foreground">
            AI-generated code is an approximation. Review layout, accessibility, and security before
            shipping.
          </p>
        </section>

        {/* RIGHT: result */}
        <section className="glass-panel min-h-[500px] space-y-4 p-5">
          {busy && <LoadingSteps />}

          {!result && !busy && <EmptyState hasImage={!!image} />}

          {result && (
            <>
              <ResultTabs result={result} />
              <div className="border-t border-border pt-4">
                <RefinementBox onSubmit={(i) => refineMut.mutate(i)} disabled={busy} />
              </div>
            </>
          )}
        </section>
      </div>
    </div>
  );
}

function EmptyState({ hasImage }: { hasImage: boolean }) {
  return (
    <div className="flex h-full min-h-[400px] flex-col items-center justify-center gap-2 text-center">
      <div className="text-sm font-medium">
        {hasImage ? "Ready when you are." : "Upload an image to begin."}
      </div>
      <div className="max-w-sm text-xs text-muted-foreground">
        {hasImage
          ? "Choose your output mode on the left and hit Generate HTML."
          : "Drop a PNG, JPG, or WebP screenshot of a UI, landing page, or component. The AI reconstructs it as clean, semantic HTML/CSS."}
      </div>
    </div>
  );
}

function errorMessage(code: string, msg: string): string {
  switch (code) {
    case "MISSING_API_KEY":
      return "MISTRAL_API_KEY is not configured on the server.";
    case "MISSING_BLOB_TOKEN":
      return "BLOB_READ_WRITE_TOKEN is not configured on the server.";
    case "AI_TIMEOUT":
      return "AI request timed out. Try a smaller image or try again.";
    case "RATE_LIMITED":
      return "Rate limited by AI provider. Please retry shortly.";
    case "AI_INVALID_RESPONSE":
      return "AI returned an unreadable response. Try again or refine your instructions.";
    case "FILE_TOO_LARGE":
    case "UNSUPPORTED_FORMAT":
    case "INVALID_FILE":
      return msg;
    default:
      return msg || "Unexpected error";
  }
}
