import { createFileRoute } from "@tanstack/react-router";

import { IndexPage } from "@/pages/index-page";

type IndexSearch = {
  project?: string;
};

export const Route = createFileRoute("/_editor/")({
  validateSearch: (search: Record<string, unknown>): IndexSearch => ({
    project: typeof search.project === "string" ? search.project : undefined,
  }),
  head: () => ({
    meta: [
      { title: "PNGtoHTMLapp — Screenshot to clean HTML" },
      {
        name: "description",
        content:
          "Upload a UI screenshot and get clean, semantic HTML and CSS generated by AI. Sandboxed preview, copy, and download.",
      },
      { property: "og:title", content: "PNGtoHTMLapp" },
      {
        property: "og:description",
        content: "Turn UI screenshots into clean, semantic HTML with AI.",
      },
    ],
  }),
  component: IndexPage,
});
