/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/_editor'
import { Route as EditorIndexRouteImport } from './routes/_editor/index'
import { Route as EditorProjectsRouteImport } from './routes/_editor/projects'
import { Route as EditorBuilderRouteImport } from './routes/_editor/builder'
import { Route as EditorProjectsProjectIdRouteImport } from './routes/_editor/projects.$projectId'

const EditorRoute = EditorRouteImport.update({
  id: '/_editor',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const EditorProjectsRoute = EditorProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => EditorRoute,
} as any)
const EditorBuilderRoute = EditorBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => EditorRoute,
} as any)
const EditorProjectsProjectIdRoute = EditorProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => EditorProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof EditorIndexRoute
  '/builder': typeof EditorBuilderRoute
  '/projects': typeof EditorProjectsRouteWithChildren
  '/projects/$projectId': typeof EditorProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/builder': typeof EditorBuilderRoute
  '/projects': typeof EditorProjectsRouteWithChildren
  '/': typeof EditorIndexRoute
  '/projects/$projectId': typeof EditorProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_editor': typeof EditorRouteWithChildren
  '/_editor/builder': typeof EditorBuilderRoute
  '/_editor/projects': typeof EditorProjectsRouteWithChildren
  '/_editor/': typeof EditorIndexRoute
  '/_editor/projects/$projectId': typeof EditorProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/builder' | '/projects' | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/builder' | '/projects' | '/' | '/projects/$projectId'
  id:
    | '__root__'
    | '/_editor'
    | '/_editor/builder'
    | '/_editor/projects'
    | '/_editor/'
    | '/_editor/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EditorRoute: typeof EditorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_editor': {
      id: '/_editor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_editor/': {
      id: '/_editor/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/_editor/projects': {
      id: '/_editor/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof EditorProjectsRouteImport
      parentRoute: typeof EditorRoute
    }
    '/_editor/builder': {
      id: '/_editor/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof EditorBuilderRouteImport
      parentRoute: typeof EditorRoute
    }
    '/_editor/projects/$projectId': {
      id: '/_editor/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof EditorProjectsProjectIdRouteImport
      parentRoute: typeof EditorProjectsRoute
    }
  }
}

interface EditorProjectsRouteChildren {
  EditorProjectsProjectIdRoute: typeof EditorProjectsProjectIdRoute
}

const EditorProjectsRouteChildren: EditorProjectsRouteChildren = {
  EditorProjectsProjectIdRoute: EditorProjectsProjectIdRoute,
}

const EditorProjectsRouteWithChildren = EditorProjectsRoute._addFileChildren(
  EditorProjectsRouteChildren,
)

interface EditorRouteChildren {
  EditorBuilderRoute: typeof EditorBuilderRoute
  EditorProjectsRoute: typeof EditorProjectsRouteWithChildren
  EditorIndexRoute: typeof EditorIndexRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorBuilderRoute: EditorBuilderRoute,
  EditorProjectsRoute: EditorProjectsRouteWithChildren,
  EditorIndexRoute: EditorIndexRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  EditorRoute: EditorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
