import type { RenderRequest } from './render-schema.js';

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

export const renderWeb24hHtml = (request: RenderRequest): string => {
  const { payload } = request;
  const brandName = escapeHtml(payload.brand.name);
  const tagline = payload.brand.tagline ? escapeHtml(payload.brand.tagline) : '';
  const primaryColor = payload.brand.primaryColor || '#0ea5e9';

  const sectionsHtml = payload.pages
    .map((page) => {
      const pageTitle = escapeHtml(page.title);
      const sectionItems = page.sections
        .map((section) => {
          const heading = escapeHtml(section.heading);
          const body = escapeHtml(section.body);
          const bullets = section.bullets
            .map((bullet) => `<li>${escapeHtml(bullet)}</li>`)
            .join('');
          const sectionCta = section.cta
            ? `<a class="btn btn-outline" href="${escapeHtml(section.cta.href)}">${escapeHtml(section.cta.label)}</a>`
            : '';

          return `
            <section id="${escapeHtml(section.id)}" class="card">
              <h3>${heading}</h3>
              <p>${body}</p>
              ${bullets ? `<ul>${bullets}</ul>` : ''}
              ${sectionCta}
            </section>
          `;
        })
        .join('\n');

      return `
        <article data-page="${escapeHtml(page.slug)}">
          <h2>${pageTitle}</h2>
          ${sectionItems}
        </article>
      `;
    })
    .join('\n');

  const cta = payload.cta;
  const ctaHtml = `<a class="btn" href="${escapeHtml(cta.href)}">${escapeHtml(cta.label)}</a>`;
  const seoTitle = escapeHtml(payload.seo.title);
  const seoDescription = escapeHtml(payload.seo.description);
  const ogTitle = escapeHtml(payload.seo.ogTitle || payload.seo.title);
  const ogDescription = escapeHtml(payload.seo.ogDescription || payload.seo.description);

  return `<!doctype html>
<html lang="sk">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${seoTitle}</title>
    <meta name="description" content="${seoDescription}" />
    <meta property="og:title" content="${ogTitle}" />
    <meta property="og:description" content="${ogDescription}" />
    <style>
      :root { --brand: ${escapeHtml(primaryColor)}; --bg: #0b1020; --card: #121a2b; --text: #e9f0ff; --muted: #a6b2cf; }
      * { box-sizing: border-box; }
      body { margin: 0; font-family: Inter, system-ui, sans-serif; background: var(--bg); color: var(--text); line-height: 1.55; }
      .wrap { max-width: 980px; margin: 0 auto; padding: 24px 18px 48px; }
      header { margin-bottom: 18px; }
      header h1 { margin: 0 0 8px; font-size: 2rem; }
      header p { margin: 0; color: var(--muted); }
      h2 { margin: 24px 0 12px; font-size: 1.4rem; }
      .card { background: var(--card); border: 1px solid #23304f; border-radius: 14px; padding: 14px 16px; margin-bottom: 12px; }
      .card h3 { margin-top: 0; }
      .card p { color: #d4def6; }
      ul { margin: 0 0 10px; padding-left: 20px; color: #d4def6; }
      .btn { display: inline-block; background: var(--brand); color: #08101f; font-weight: 700; text-decoration: none; border-radius: 10px; padding: 10px 14px; }
      .btn-outline { background: transparent; color: var(--text); border: 1px solid #2f4370; }
      .cta { margin-top: 20px; padding: 18px; border: 1px solid #2f4370; border-radius: 14px; text-align: center; }
      footer { margin-top: 28px; color: var(--muted); font-size: 0.9rem; text-align: center; }
    </style>
  </head>
  <body>
    <main class="wrap">
      <header>
        <h1>${brandName}</h1>
        ${tagline ? `<p>${tagline}</p>` : ''}
      </header>
      ${sectionsHtml}
      <section class="cta">
        ${ctaHtml}
      </section>
      <footer>
        Generated by VibeCraft render artifact API.
      </footer>
    </main>
  </body>
</html>`;
};
